name = "HiddenMarkovModels"
uuid = "84ca31d5-effc-45e0-bfda-5a68cd981f47"
authors = ["Guillaume Dalle"]
version = "0.4.2"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[weakdeps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[extensions]
HiddenMarkovModelsDistributionsExt = "Distributions"

[compat]
ArgCheck = "2.3"
ChainRulesCore = "1.16"
DensityInterface = "0.4"
Distributions = "0.25"
DocStringExtensions = "0.9"
FillArrays = "1"
LinearAlgebra = "1"
PrecompileTools = "1.1"
Random = "1"
SparseArrays = "1"
StatsAPI = "1.6"
StatsFuns = "1.3"
julia = "1.9"
